name = "SymbolicArrays"
uuid = "89b603bc-5db9-4369-8dcc-3f453fd67cca"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]
version = "0.1.0"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Moshi = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"

[weakdeps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[extensions]
SymbolicArraysAbstractTreesExt = "AbstractTrees"

[compat]
AbstractTrees = "0.4"
Aqua = "0.8"
AutoHashEquals = "2"
IterTools = "1"
Moshi = "0.3"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
